Repository elastic/elastic-transport-python, pull requests merged in 2024-05, with the labels that each got.

#163 Remove last uses of mock
  setup.py
  tests/node/test_http_requests.py
  tests/node/test_http_urllib3.py
Labels: Category: Enhancement, Area: Tests

#164 Adopt requests new get_connection API
  .github/workflows/ci.yml
  elastic_transport/_node/_http_requests.py
  noxfile.py
  requirements-min.txt
Labels: backport 8.13, backport 8.14

#115 Fix TypeError when NodePool._dead_nodes timestamps are not unique
  elastic_transport/_node/_base.py
Labels: Category: Bug, backport 8.13, Area: Client, backport 8.14
